"""Generate the complete stored-schema documentation for data/FHA_Unified_Database.json.

The hand-maintained portion of data/dictionaries/fha_unified_database.md documents the 28
model-classified fields. The stored records carry more keys than that (screening metadata, source
flags, refresh fields), and record-level key counts vary by tier. This script derives, directly
from the committed database:

- data/FHA_Unified_Database.schema.json  — machine-readable JSON Schema (draft 2020-12) covering
  every observed key, its observed types, nullability, and enumerated values for low-cardinality
  string fields;
- the "Complete Stored Schema" section of data/dictionaries/fha_unified_database.md — a generated
  table of all observed keys with types, presence and null rates overall and within T1
  (screened-in) and T2 (disability-screened), distinct-value counts, and observed values for
  enum-like fields. The section is delimited by the two GENERATED marker comments and is rewritten
  in place; everything outside the markers is hand-maintained and is left untouched.

Regenerate after any database change:  python scripts/make_data_dictionary.py
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

# Tier membership uses the canonical predicates so this generator cannot drift from the
# filters the analysis scripts apply (analysis_filters normalizes protected_classes case
# and whitespace; a local re-implementation undercounted T2 by one record).
from analysis_filters import is_screened_in as is_t1, is_t2_canonical as is_t2

REPO = Path(__file__).resolve().parents[1]
DB = REPO / "data" / "FHA_Unified_Database.json"
SCHEMA_OUT = REPO / "data" / "FHA_Unified_Database.schema.json"
MD_OUT = REPO / "data" / "dictionaries" / "fha_unified_database.md"
MD_BEGIN = "<!-- BEGIN GENERATED: complete stored schema -->"
MD_END = "<!-- END GENERATED: complete stored schema -->"

ENUM_MAX = 24  # string fields with at most this many distinct non-null values are enumerated


def jtype(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "boolean"
    if isinstance(v, int):
        return "integer"
    if isinstance(v, float):
        return "number"
    if isinstance(v, str):
        return "string"
    if isinstance(v, list):
        return "array"
    if isinstance(v, dict):
        return "object"
    return type(v).__name__


def main() -> None:
    records = json.loads(DB.read_text(encoding="utf-8"))
    n = len(records)
    t1 = [r for r in records if is_t1(r)]
    t2 = [r for r in records if is_t2(r)]

    stats: dict[str, dict] = defaultdict(
        lambda: {"types": Counter(), "present": 0, "null": 0, "t1_present": 0, "t2_present": 0,
                 "values": Counter(), "enumerable": True}
    )
    for r in records:
        for k, v in r.items():
            s = stats[k]
            s["present"] += 1
            s["types"][jtype(v)] += 1
            if v is None:
                s["null"] += 1
            elif isinstance(v, str):
                if len(s["values"]) <= ENUM_MAX:
                    s["values"][v] += 1
                if len(s["values"]) > ENUM_MAX:
                    s["enumerable"] = False
            else:
                s["enumerable"] = s["enumerable"] and isinstance(v, (bool, int))
    for r in t1:
        for k in r:
            stats[k]["t1_present"] += 1
    for r in t2:
        for k in r:
            stats[k]["t2_present"] += 1

    # --- JSON Schema ---
    props = {}
    for k in sorted(stats):
        s = stats[k]
        types = sorted(s["types"])
        prop: dict = {"type": types if len(types) > 1 else types[0]}
        if s["enumerable"] and s["values"] and "string" in types:
            enum = sorted(s["values"])
            if "null" in types:
                prop["enum"] = enum + [None]
            else:
                prop["enum"] = enum
        prop["description"] = (
            f"present in {s['present']}/{n} records; null in {s['null']}"
        )
        props[k] = prop
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "FHA Unified Database record",
        "description": (
            "Generated by scripts/make_data_dictionary.py from the committed canonical database. "
            "Records are heterogeneous: screened-out records carry few keys; screened-in records "
            "carry the full classification schema. No key is universally required."
        ),
        "type": "object",
        "properties": props,
        "additionalProperties": False,
    }
    SCHEMA_OUT.write_text(
        json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8", newline="\n",
    )

    # --- Markdown table ---
    lines = [
        "## Data Dictionary — Complete Stored Schema (generated)",
        "",
        f"Generated by `scripts/make_data_dictionary.py` from `data/FHA_Unified_Database.json` "
        f"({n:,} records; T1 screened-in = {len(t1):,}; T2 disability-screened = {len(t2):,}).",
        "",
        "This is the complete observed key inventory: it covers every stored key, including"
        " screening and source metadata, with presence/null rates by tier."
        " Machine-readable schema: [`../FHA_Unified_Database.schema.json`](../FHA_Unified_Database.schema.json).",
        "",
        "Records are heterogeneous by design: screened-out records (screening_result == \"NO\" or"
        " unscreened retrieval failures) carry as few as 4 keys; fully classified records carry up"
        " to 44.",
        "",
        "| Key | Types | Present (all) | Null (all) | Present T1 | Present T2 | Distinct values | Enumerated values |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for k in sorted(stats):
        s = stats[k]
        types = "/".join(sorted(s["types"]))
        enum = ""
        # values counting stops once a field exceeds ENUM_MAX distinct values, so the count
        # is exact only for enumerable fields; otherwise report it as a floor.
        if not s["values"]:
            distinct = ""
        elif s["enumerable"]:
            distinct = str(len(s["values"]))
        else:
            distinct = f">{ENUM_MAX}"
        if s["enumerable"] and s["values"]:
            enum = "; ".join(f"`{v}`" for v in sorted(s["values"]))
            if len(enum) > 240:
                enum = enum[:240] + "…"
        lines.append(
            f"| `{k}` | {types} | {s['present']}/{n} | {s['null']} | "
            f"{s['t1_present']}/{len(t1)} | {s['t2_present']}/{len(t2)} | {distinct} | {enum} |"
        )
    lines += [
        "",
        "Tier predicates (canonical, from `scripts/analysis_filters.py`): "
        "T1 = `screening_result != \"NO\"` AND `case_name` present; on this snapshot that is "
        "equivalent to `screening_result == \"YES\"` (2,690 records either way). "
        "T2 = T1 AND (`\"disability\" in protected_classes` OR `disability_alleged` OR `is_ra_case`).",
    ]

    # Rewrite only the delimited section; the hand-maintained text around it is
    # the dictionary proper and must survive regeneration untouched.
    page = MD_OUT.read_text(encoding="utf-8").split("\n")
    try:
        b = page.index(MD_BEGIN)
        e = page.index(MD_END)
    except ValueError:
        raise SystemExit(
            f"{MD_OUT.relative_to(REPO)}: generated-section markers not found; "
            "expected the BEGIN/END GENERATED comment pair"
        )
    page[b + 1:e] = [""] + lines + [""]
    MD_OUT.write_text("\n".join(page), encoding="utf-8", newline="\n")
    print(f"wrote {SCHEMA_OUT.relative_to(REPO)} and the generated section of "
          f"{MD_OUT.relative_to(REPO)}: {len(stats)} keys")


if __name__ == "__main__":
    main()
